### ISSUE TITLE
Workflow for printing out large maps (A0) on several small papers (A4)?

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/sketch-map-tool#231]
> is there an option to be able to print out larger maps (like on A-0) in several A-4 pieces and paste them together? Because we dont always have access to large format plotters, so being able to patch it together with A-4 formats will be useful.

**Comment by mhhd2020** [comment]
Basically I think it should work if you instruct your PDF viewer to print it on multiple A4s and glue/put them together such that there are no significant borders between the single pages. If the printer adds some border around the parts of the map on each page, they would of course have to be cut away before putting everything together. The poster mode of Adobe Reader [seems to be a simple solution for printing A0 on multiple A4](https://graphicdesign.stackexchange.com/questions/55922/how-to-print-a-pdf-with-large-pages-onto-multiple-smaller-sheets-of-paper). However, as far as I know, we did not test yet whether splitting up one A0 map on multiple A4s leads to problems with detecting the map on a photo and should definitely check this
