### ISSUE TITLE
Digitize fails on A1 map frame. Uploaded image was a small screenshot. Error occurred on georeference and sketch detection.

### ISSUE THREAD

**Issue by rtroilo** [GIScience/sketch-map-tool#277]
Error Details
OpenCV(4.8.0) /io/opencv/modules/features2d/src/matchers.cpp:860: error: (-215:Assertion failed) trainDescCollection[iIdx].rows < IMGIDX_ONE in function 'knnMatchImpl' 
![sketch-map](https://github.com/GIScience/sketch-map-tool/assets/4215514/3fe80e4b-d251-49a4-8063-8c4621c4e9a2)

**Comment by matthiasschaub** [comment]
Same as #265 ?
