### ISSUE TITLE
ui: update text to not mention OSM in the case where satellite imagery has been used as background map

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/sketch-map-tool#370]
![image](https://github.com/GIScience/sketch-map-tool/assets/83658582/2cee8eee-03d3-46a1-8f3c-9ba4ef9a3a6a)

**Comment by anneschauss** [comment]
maybe just: We have created the Sketch Map template that you can use for offline participatory mapping. We used **ESRI World Imagery (add link)** to create a high resolution printable map for you, 
...
