### ISSUE TITLE
Use UUIDs for output file locations and status updates

### ISSUE THREAD

**Issue by mhhd2020** [GIScience/sketch-map-tool#40]
Instead of different combinations of bboxes, paper formats, times, random character sequences etc. use UUIDs for storing output files, their status updates, and retrieving them. As a first step directories with the UUID as name can be used to achieve that.

**Comment by matthiasschaub** [comment]
`Celery` is now been used to store results into a backend (currently redis=
https://github.com/GIScience/sketch-map-tool/pull/85
