### ISSUE TITLE
Change the way in which bounding boxes are selected

### ISSUE THREAD

**Issue by mhhd2020** [GIScience/sketch-map-tool#42]
Map UI: Selection of AOI will be through a clearly visible box (rectangle) in a ratio corresponding to the chosen paper format and orientation (portrait vs. landscape). The map is then dragged beneath this box to select the area. This makes most of the leaflet tools (drawing a bbox, moving a bbox, moving a point, deleting a bbox) obsolete, but the search function still needs to be provided.

**Comment by matthiasschaub** [comment]
Related to https://github.com/GIScience/sketch-map-tool/issues/47
